# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y12xQR1R6y6vffdLyDKB8Bzr42ORZFJN
"""

# going to use python to make a snake game

class Snake:

  def __init__(self,body,direction):
    self.body=body
    self.direction=direction

  def take_step(self,position):
    # this is some python trickery, but basically, body[1:] this removes the first element, then the +
    #[] position will add an element to the end. wild
    self.body=self.body[1:] + [position]

  def set_direction(self,direction):
    self.direction=direction

  def head(self):
    return self.body[-1]




#class Apple:
class Game:

  def __init__(self,height, width):
    self.height=height
    self.width=width
    self.snake= Snake([(1,1),(1,2),(1,3),(1,4)],DOWN)

  def command(self,direction):
    self.snake.set_direction(direction)
    head=self.snake.head()

    newHead=(head[0]+direction[0],head[1]+direction[1])
    self.snake.take_step(newHead)


  def render(self):
    print("Height: ",  self.height)
    print("Width: ", self.width)

    matrix=self.board_matrix()

    # print the matrix
    for i in range(self.height):
      print("")
      for j in range(self.width):
        if (i==0 or i==self.height-1) and (j==0 or j==self.width-1):
          print("+",end="")
        elif i==0 or i==self.height-1:
          print("-",end="")
        elif j==0 or j==self.width-1:
          print("|",end="")
        else:
          if matrix[i][j]=="O":

            print("O",end="")

          elif matrix[i][j]=="X":
            print("X", end="")

          else:
            print(" ",end="")


  def board_matrix(self):
    # return matrix
    matrix= [[None] * self.width for _ in range(self.height)]



    for row,col in self.snake.body:
      matrix[row][col]= "O"
      row2,col2= row,col
    matrix[row2][col2]="X"




    return matrix





RIGHT= (0,1)
LEFT=(0,-1)
UP=(-1,0)
DOWN=(1,0)






game=Game(20,20)
game.render()

# prob want to do a while loop, and for each key pressed, just change the board to the direction ive gone or something
play=True
while play:
  print("")
  dirt=input("press 'wsda' to move the snake in a direction or 'q' to quite: ")

  if dirt=='w':
    game.command(UP)
    game.render()
  elif dirt=='s':
    game.command(DOWN)
    game.render()
  elif dirt=='a':
    game.command(LEFT)
    game.render()
  elif dirt=='d':
    game.command(RIGHT)
    game.render()
  elif dirt=='q':
    play=False
    print("Thanks for Playing!")

