# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y12xQR1R6y6vffdLyDKB8Bzr42ORZFJN
"""

# going to use python to make a snake game, fuck it

class Snake:

  def __init__(self,body,direction):
    self.body=body
    self.direction=direction

  def take_step(self,position):
    # this is some python trickery, but basically, body[1:] this removes the first element, then the +
    #[] position will add an element to the end. wild
    self.body=self.body[1:] + [position]

  def set_direction(self,direction):
    self.direction=direction

  def head(self):
    return self.body[-1]




#class Apple:
class Game:

  def __init__(self,height, width):
    self.height=height
    self.width=width
    self.snake= Snake([(1,1),(1,2),(1,3),(1,4)],DOWN)

  def render(self):
    print("Height: ",  self.height)
    print("Width: ", self.width)

    matrix=self.board_matrix()
    print(matrix)
    # print the matrix
    for i in range(self.height):
      print("")
      for j in range(self.width):
        if (i==0 or i==self.height-1) and (j==0 or j==self.width-1):
          print("+",end="")
        elif i==0 or i==self.height-1:
          print("-",end="")
        elif j==0 or j==self.width-1:
          print("|",end="")
        else:
          if matrix[i][j]=="O":

            print("O",end="")

          elif matrix[i][j]=="X":
            print("X", end="")

          else:
            print(" ",end="")


  def board_matrix(self):
    # return matrix
    matrix= [[None] * self.width for _ in range(self.height)]



    for row,col in self.snake.body:
      matrix[row][col]= "O"
      row2,col2= row,col
    matrix[row2][col2]="X"




    return matrix





UP= (0,1)
DOWN=(0,-1)
LEFT=(-1,0)
RIGHT=(1,0)






game=Game(20,20)
game.render()

